### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Waleed-KH** [utilixjs/utilix#24]
This post to tack near-term plans for [utilix](https://github.com/utilixjs/utilix)

## General
- [x] Documentation using [VitePress](https://vitepress.dev/) (🔃 In-progress)
  - [x] Auto generate docs from source file TSDoc
  - [ ] Interactive playground, similar to [MDN](https://developer.mozilla.org/en-US/blog/introducing-the-mdn-playground/#under_the_hood)
- [ ] Modules meta files (changelog, since v., last update, credit, contributors ...) & it's generator, will be required for the docs
- [ ] New Logo? the current logo was ganarated using Bing (DALL·E 🤖), I like it, but I'm open to suggestions.

 ## v0.4

- [x] basics
  - [x] `isNumeric` d17d751e4b7db9510a309e673756034cdfc8ee0e
- [x] async
  - [x] `delay` 78db2f89202688629d6d2f6c42850005bc922073
- [x] time
  - [x] `TimeSpan` format, parsing & some improvements f8b1c704755064e75370ccfb78954d2985224382, ff2d816626c09d4def619297c4ca943b63c7da1b, 71fca9353475d49b4be9eb2cc00422e3b623d99e, 068dfc7b39c27ce4479e9b902cad0091c7210d3a
  - [x] `Elapse` drift adjusting option and some improvements c8819ed 37572c4 0fbb8f2

 ## v0.5

- [ ] object
- [ ] array
- [ ] function
- [ ] types (🔃 In-progress)
- [ ] async
  - [ ] `worker` or `promiseWorker` (🔃 In-progress)

 ## v0.6

- [ ] browser
  - [ ] `storage` or `varStorage` (represnt a keyed value stored in `localStorage` or `sessionStorage`)
  - [ ] `cssSwitch`
  - [ ] `mediaQuery`
  - [ ] `colorMode`
  - [ ] `dark`
